name = "confessions of a bisexual teen"
license = "MIT"
homepage = "https://github.com/natarajmb/charaka-hugo-theme"

[params]

[author]
  name = "Nataraj Basappa"
  homepage = "https://www.natarajmb.com"
